import type { IconKind } from "./KindIcon";

export const metadataIconMap: Record<string, IconKind> = {
  MPropertyFriendlyName: "meta-tag",
  MPropertyDescription: "meta-note",
  MNetworkEnable: "meta-broadcast",
  MNetworkVarNames: "meta-variable",
  MNetworkChangeCallback: "meta-broadcast",
  MNetworkUserGroup: "meta-broadcast",
  MNetworkIncludeByName: "meta-broadcast",
  MNetworkExcludeByName: "meta-broadcast",
  MNetworkExcludeByUserGroup: "meta-broadcast",
  MNetworkIncludeByUserGroup: "meta-broadcast",
  MNetworkBitCount: "meta-broadcast",
  MNetworkMinValue: "meta-broadcast",
  MNetworkMaxValue: "meta-broadcast",
  MNetworkPriority: "meta-broadcast",
  MNetworkEncodeFlags: "meta-broadcast",
  MNetworkEncoder: "meta-broadcast",
  MNetworkSerializer: "meta-broadcast",
  MNetworkAlias: "meta-broadcast",
  MNetworkOverride: "meta-broadcast",
  MNetworkSendProxyRecipientsFilter: "meta-broadcast",
  MNetworkTypeAlias: "meta-broadcast",
  MNetworkVarTypeOverride: "meta-broadcast",
  MNetworkUserGroupProxy: "meta-broadcast",
  MNetworkReplayCompatField: "meta-broadcast",
  MGetKV3ClassDefaults: "meta-variable",
  MKV3TransferName: "meta-tag",
  MAlternateSemanticName: "meta-tag",
  MNotSaved: "meta-discard",
  MPropertySuppressExpr: "meta-eye-closed",
  MPropertySuppressField: "meta-eye-closed",
  MPropertySuppressEnumerator: "meta-eye-closed",
  MPropertyHideField: "meta-eye-closed",
  MPropertyGroupName: "meta-folder",
  MPropertyStartGroup: "meta-folder",
};
